### ISSUE TITLE
missing index.html / localhost:8080

### ISSUE THREAD

**Issue by Remownz** [GarrettLevine/ts-node-react-starter#3]
Hi @GarrettLevine,

i'm looking for a simple ts node react starter and found your project. So far i think this is what i'm looking for. I have a few questions which you hopefully can enlighten.

1. there is no index.html generated in public, so the app is only running with webpack.dev server?
2. Your readme says "go to your localhost:3000" -- shoudn't that be localhost:8080? - localhost:3000 can't serve a index.html

thanks for your work btw!

**Comment by GarrettLevine** [comment]
hey! Sorry @Remownz . I haven't updated this project unfortunately, and I haven't made some changes that I've made locally! You're totally right re: the public html, and I think this project has some mistakes in the webpack proxy - let me see if I can't fix 'em up really quickly for ya!

**Comment by GarrettLevine** [comment]
@Remownz I think I've made the changes necessary! Let me know if you have any issues. You will still go to your `localhost:3000` to access your app! 💃

**Comment by GarrettLevine** [comment]
@Remownz now it should be good to go! :dancing_men:  Just had to fix a small style loader thing!
